### ISSUE TITLE
an error keeps coming up every time I run escape.matrix or other functions in this package

### ISSUE THREAD

**Issue by RosyGH** [ncborcherding/escape#100]
enrichment.scores <- escape.matrix(pbmc_small, 
+                                    gene.sets = GS.hallmark, 
+                                    groups = 1000, 
+                                    min.size = 5)
[1] "Using sets of 1000 cells. Running 1 times."
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘gsva’ for signature ‘"missing", "missing"’

**Comment by ncborcherding** [comment]
This is an issue with your GSVA version - pleas check out #88 

Thanks,
Nick

**Comment by RosyGH** [comment]
您好，我最近正在忙碌中，无法亲自回复您的邮件。我将在忙碌结束后，尽快给您回复。

**Comment by RosyGH** [comment]
Thank you so much!
