### ISSUE TITLE
Issue with runEscape() and counts Layer

### ISSUE THREAD

**Issue by monikaramos** [ncborcherding/escape#114]
Hi there, 

I'm encountering the following error when running runEscape() **but not** when I run escape.matrix()

pbmc_small <- runEscape(pbmc_small, 
+                         method = "ssGSEA",
+                         gene.sets = gene.sets, 
+                         groups = 1000, 
+                         min.size = 5,
+                         new.assay.name = "escape.ssGSEA")
[1] "Using sets of 1000 cells. Running 1 times."
Warning: Layer counts isn't present in the assay object; returning NULL

I am working with a seurat v5 object and it will successfully run when I use the escape.matrix function. Unfortunately, I would like to be able to use the runEscape function so I can have more ease with and more plotting functions. Please advise, thank you!

I've updated the escape package too.

Version R 4.4

**Comment by ncborcherding** [comment]
Hey @monikaramos, 

This appears to be an issue with the Seurat version - find out more info [here](https://github.com/satijalab/seurat/issues/8938). 

In the meantime, you can add the output of ```escape.matrix()``` to your Seurat object using: 

```
new.assay <- CreateAssayObject(data = as.matrix(t(enrichment.results))))

SeuratObj[["escape"]] <- new.assay)
```

Hope that helps, let me know if you have any other questions. 

Thanks,
Nick

**Comment by monikaramos** [comment]
Thank you for your response! Unfortunately, in doing so I still get the
following warning, is this okay?

> new.assay <- CreateAssayObject(data = as.matrix(t(enrichment.scores)))
> pbmc_small[["escape"]] <- new.assay
Warning: Layer counts isn't present in the assay object; returning NULL

Also, is the enrichment score calculation done on the seurat v5's count
assay (raw) or the data assay (normalized)?

thanks for your help.

**Comment by yeroslaviz** [comment]
I'm getting the same error here. Was this solved?
