### ISSUE TITLE
genesets from msigdb

### ISSUE THREAD

**Issue by alicekao1118** [ncborcherding/escape#115]
Hi Nick,

Thanks for developing this useful tool! I have a question about the database I pulled from Msigdb database. I tried to get

`gene.set.1 <- getGeneSets(species="Homo sapiens",
                          library=c("C2"),
                          subcategory = c("CP")
                          )`

But the output is only 29 pathways, which is differnet from the website's 3917.
https://www.gsea-msigdb.org/gsea/msigdb/collections.jsp

Also, I'm wondering if there's a way to get down further into the smaller subset, like `PID subset of CP`, `KEGG_LEGACY subset of CP`. 

I'm using escape v2.0.0

Thanks,
Alice

**Comment by ncborcherding** [comment]
Hey Alice, 

Thanks for reaching out - this is a confusing point and I need to improve the documentation. There is an argument in ```escpae.matrix()``` and ```runEscape()``` **min.size** = 5. This means it will automatically remove gene sets that do not have at least 5 genes in the input data. I would not have guessed there would be a order of magnitude reduction though - I would make sure your gene symbols are matching between the ```gene.set.1``` and the single-cell object. 

For the second question - this is more dictated by how [msigDBR](https://cran.r-project.org/web/packages/msigdbr/vignettes/msigdbr-intro.html) stores data. You can see if it possible. from the above package. 

Thanks for reaching out,
Nick
