### ISSUE TITLE
runEscape with method="GSVA" takes more then 10h and did not finish

### ISSUE THREAD

**Issue by al3xmlt030** [ncborcherding/escape#116]
Hello,

Thank you for developing this tool! I've been using `runEscape` with different methods to compare the results. Unfortunately, most methods run within 20 minutes to an hour, except for GSVA. I left the following code running overnight with around 160,000 cells, but it didn’t complete:

```
seurat.obj<- runEscape(seurat.obj, 
                        method = "GSVA",
                        gene.sets = GS.hallmark, 
                        groups = 1000, 
                        min.size = 5,
                        new.assay.name = "escape.GSVA")

```
Is there any insight into why this might be happening?

**Comment by ncborcherding** [comment]
@al3xmlt030 

Thanks for reaching out - unfortunately, the ranking method in GSVA is slower than the other methods. One thing that might help with the time is parallel processing with the **BPPARAM** parameter in ```runEscape()```. There was an issue with this parameter in ```runeEscape()```, so make you have have the most recent version: 

```
devtools::install_github("ncborcherding/escape")
```

You might also try subsetting your data if you are comparing methodology, all the methods are performing gene set enrichment on each cell, so 160,000 is a lot of calculations. 

Nick
