### ISSUE TITLE
statistcs

### ISSUE THREAD

**Issue by EAC-T** [ncborcherding/escape#12]
Thank you a lot for creating a tool that is compatible with Seurat and SCE objects.
I used escape and got some interesting results, however, in the vignette I didn't see any section on how to find the statistically significant pathways. Is there a way to do so using escape or any other tools?

Thank you again!

**Comment by ncborcherding** [comment]
Hey EAC-T,

Great question!

So yes this is an active area of development - there is an initial significance test that can use T.test, ANOVA, and lm.fit from the limma R package (what GSV package suggests) - I have noticed the lm.fit is likely overfitting the data and with the n size of single-cell, nothing I have found quite works yet. 

<img width="647" alt="Screen Shot 2020-12-07 at 2 50 28 PM" src="https://user-images.githubusercontent.com/22754118/101403997-a38dd600-389b-11eb-87aa-da24ceeed4a9.png">

**Comment by EAC-T** [comment]
Thank you for pointing out the section on significance. 
I just tried and yes I guess I got all 50 pathway being significant, which I think is not accurate.
The traditional GSEA software for example will generate a p-value, do they use another method to do it? would you know?
Thank you anyway

**Comment by ncborcherding** [comment]
Hey EAC-T,

The statistics employed for the traditional GSEA is not appropriate here - it relies on group-defined enrichment as opposed to single-sample (like in escape). I personally use the ANOVA and T-test methods, which seems to increase the specificity at least. 

```
output <- getSignificance(ES2, group = "Type", fit = "T.test")
```

Nick

**Comment by EAC-T** [comment]
Thank you a lot Nick!
