### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by Sirin24** [ncborcherding/escape#121]
Hello, I have generated DEGs from findmarkers() in Seurat between fibroblast_disease and fibroblast_control. I also did this for other celltypes in metadata column named celltype_condition  

Now, how to use this package to do gene set enrichment analysis to find upregulated and downregulated pathways ? 
If this format is not suitable  as input to the tool then how to prepare my object for such comparisons ?  
It it done for each celltype_condition alone then I would compare the healthy and the control?

I will appreciate your help and looking forward to using your tool. Thanks.

**Comment by ncborcherding** [comment]
Hey @Sirin24,

That is slightly different then what escape was designed for. Escape will calculate the enrichment values for the individual cells and from there, you can find differential gene sets based on the individual cell distributions.

If you want to use a pre-ranked gene list for GSEA you can check out [clusterProfiler](https://bioconductor.org/packages/release/bioc/html/clusterProfiler.html) or f[GSEA](https://bioconductor.org/packages/release/bioc/html/fgsea.html).

Nick

**Comment by Sirin24** [comment]
Thank you. is it possible to use this tool to compare different conditions? is there a vignette to do that? should I be processing each condition alone or combined object?
