### ISSUE TITLE
getSignificance() question

### ISSUE THREAD

**Issue by ayin0510** [ncborcherding/escape#125]
Hi Nick, 

I am following along with this vignette https://bioconductor.statistik.tu-dortmund.de/packages/3.13/bioc/vignettes/escape/inst/doc/vignette.html#3_Enrichment. Is the getSignificance() function still available with the current version of escape? 

Many thanks, 
Anna

**Comment by ncborcherding** [comment]
Hey @ayin0510 

In the most recent version of escape (>=2.0), we have dropped ```getSignificance()``` in favor of other packages with statistical support for differential analysis. If you are using the bioc3.13 release of escape, it still should be in there. 

Nick
