### ISSUE TITLE
No escape.matrix or runEscape function

### ISSUE THREAD

**Issue by kangjiajinlong** [ncborcherding/escape#127]
Hello,

I installed the escape package with BiocManager::install("escape"). It seems that there is no escape.matrix or runEscape function as shown in the example code. I could only find enrichIt function, which also seems to be incompatible with Seurat V5.

Thanks,
Jack

**Comment by ncborcherding** [comment]
Hey Jack, 

This is due to the version of BioCondcutor you are installing from - you are installing an outdated release.

```
BiocManager::install(version="3.19")
BiocManager::install("escape")
```
Hope that helps and let me know if you have any other issues. 

Nick
