### ISSUE TITLE
Unable to find an inherited method for function ‘gsva’ for signature ‘"missing", "missing"’

### ISSUE THREAD

**Issue by kangjiajinlong** [ncborcherding/escape#128]
Hello,

I ran escape using the following code but encountered errors that I cannot resolve:

library(escape)
H <- getGeneSets(library="H")

DefaultAssay(obj.sub) <- "RNA"
obj.sub <- runEscape(obj.sub, method = "ssGSEA",gene.sets = H, groups = 5000, min.size = 5,new.assay.name="escape.H")

[1] "Using sets of 5000 cells. Running 17 times."
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘gsva’ for signature ‘"missing", "missing"’

Could you kindly look into this issue?

Jack

**Comment by ncborcherding** [comment]
Hey Jack, 

You will need to update your version of GSVA - please check out #88 

Nick

**Comment by kangjiajinlong** [comment]
Can I use BiocManager:install("GSVA",force=T)?

**Comment by kangjiajinlong** [comment]
I tried your suggesting devtools::install_github("rcastelo/GSVA"). The process crashed when install "SpatialExperiment":

* installing *source* package ‘SpatialExperiment’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/jkang5/R/ubuntu/4.3.1/magick/libs/magick.so':
  libMagick++-6.Q16.so.8: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
