### ISSUE TITLE
Results of getSignificance with ANOVA

### ISSUE THREAD

**Issue by hwi1208** [ncborcherding/escape#129]
The results showed pairwise comparisons among groups, so is it automatically calculated? If so, what comparisons are used in this analysis?

**Comment by ncborcherding** [comment]
@hwi1208, 

```getSignificance()``` using the ANOVA will automatically calculate the individual comparisons using the ```TukeyHSD()``` function in R. I should mention that we have deprecated ```getSignificance()``` in the newer versions of escape as there are a number of open source methods with improved statistical rigor. 

Thanks,
Nick
