### ISSUE TITLE
Statistical significance of pathways across clusters

### ISSUE THREAD

**Issue by YuliaInn** [ncborcherding/escape#13]
I am trying to compare pathway/gene sets enrichment across the clusters of my scRNA-seq data obtained earlier from Seurat V3 package. But for the significance test, when I try to use ANOVA on my seurat clusters, I get an error:

`output <- getSignificance(ES, group="seurat_clusters", fit = "ANOVA")

Error in `[.data.frame`(enriched, , group) : undefined columns selected`

**Comment by ncborcherding** [comment]
Hey Yulialnn,

The error code looks like the "group" parameter is not in your ES object. Have you attached your meta data to the output ES?

you can check with:
```
head(ES[,"seurat_clusters"])
```

Nick

**Comment by YuliaInn** [comment]
Oh, thank you. My bad, I should have atached clusters to the ES
`ES2 <- data.frame(MU150PDXThgFiltered[[]], Idents(MU150PDXThgFiltered))`
it works now
