### ISSUE TITLE
Median values for heatmapEnrichment()

### ISSUE THREAD

**Issue by ayin0510** [ncborcherding/escape#130]
Hi Nick, 

Is there any way to display the median enrichment scores by cell type rather than the mean for the heatmaps? Thanks so much!

**Comment by ncborcherding** [comment]
Hey @ayin0510 

Unfortunately, there is not, but it is a good suggestion. I will add it as an enhancement the next time I do a release. 

Thanks for reaching out,
Nick

**Comment by ncborcherding** [comment]
Quick fix in main branch. I will push it to bioconductor too when the 3.20 release settles down

**Comment by ayin0510** [comment]
Thanks so much!
