### ISSUE TITLE
Error when running enrichIt

### ISSUE THREAD

**Issue by tomthomas3000** [ncborcherding/escape#20]
I was trying to run escape on a list of genes (Formal class GeneSet) I supplied to an expression matrix. I received the following error: 

[1] "Using sets of 1000 cells. Running 1 times."
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘gsva’ for signature ‘"matrix", "character"’

I would very grateful for any advice you can provide. Installed packages and versions below:

                                 Package    Version
abind                               abind      1.4-5
annotate                         annotate     1.68.0
AnnotationDbi               AnnotationDbi     1.52.0
askpass                           askpass        1.1
AUCell                             AUCell     1.12.0
base64enc                       base64enc      0.1-3
BH                                     BH   1.75.0-0
Biobase                           Biobase     2.50.0
BiocGenerics                 BiocGenerics     0.36.1
BiocManager                   BiocManager    1.30.12
BiocParallel                 BiocParallel     1.24.1
BiocVersion                   BiocVersion     3.12.0
bit                                   bit      4.0.4
bit64                               bit64      4.0.5
bitops                             bitops      1.0-6
blob                                 blob      1.2.1
brew                                 brew      1.0-6
brio                                 brio      1.1.1
bslib                               bslib      0.2.4
cachem                             cachem      1.0.4
callr                               callr      3.6.0
caTools                           caTools     1.18.2
cli                                   cli      2.4.0
clipr                               clipr      0.7.1
colorspace                     colorspace      2.0-0
commonmark                     commonmark        1.7
cowplot                           cowplot      1.1.1
cpp11                               cpp11      0.2.7
crayon                             crayon      1.4.1
credentials                   credentials      1.3.0
crosstalk                       crosstalk      1.1.1
curl                                 curl        4.3
data.table                     data.table     1.14.0
DBI                                   DBI      1.1.1
DelayedArray                 DelayedArray     0.16.3
deldir                             deldir     0.2-10
desc                                 desc      1.3.0
devtools                         devtools      2.4.0
diffobj                           diffobj      0.3.4
digest                             digest     0.6.27
dplyr                               dplyr      1.0.5
dqrng                               dqrng      0.2.1
ellipsis                         ellipsis      0.3.1
escape                             escape      1.1.1
evaluate                         evaluate       0.14
fansi                               fansi      0.4.2
farver                             farver      2.1.0
fastmap                           fastmap      1.1.0
fitdistrplus                 fitdistrplus      1.1-3
FNN                                   FNN      1.1.3
formatR                           formatR        1.9
fs                                     fs      1.5.0
futile.logger               futile.logger      1.4.3
futile.options             futile.options      1.0.1
future                             future     1.21.0
future.apply                 future.apply      1.7.0
generics                         generics      0.1.0
GenomeInfoDb                 GenomeInfoDb     1.26.7
GenomeInfoDbData         GenomeInfoDbData      1.2.4
GenomicRanges               GenomicRanges     1.42.0
gert                                 gert      1.3.0
ggplot2                           ggplot2      3.3.3
ggrepel                           ggrepel      0.9.1
ggridges                         ggridges      0.5.3
gh                                     gh      1.2.1
gitcreds                         gitcreds      0.1.1
globals                           globals     0.14.0
glue                                 glue      1.4.2
goftest                           goftest      1.2-2
gplots                             gplots      3.1.1
graph                               graph     1.68.0
gridExtra                       gridExtra        2.3
GSEABase                         GSEABase     1.52.1
GSVA                                 GSVA     1.38.2
gtable                             gtable      0.3.0
gtools                             gtools      3.8.2
highr                               highr        0.9
htmltools                       htmltools    0.5.1.1
htmlwidgets                   htmlwidgets      1.5.3
httpuv                             httpuv      1.5.5
httr                                 httr      1.4.2
ica                                   ica      1.0-2
igraph                             igraph      1.2.6
ini                                   ini      0.3.1
IRanges                           IRanges     2.24.1
irlba                               irlba      2.3.3
isoband                           isoband      0.2.4
jquerylib                       jquerylib      0.1.3
jsonlite                         jsonlite      1.7.2
kernlab                           kernlab     0.9-29
knitr                               knitr       1.32
labeling                         labeling      0.4.2
lambda.r                         lambda.r      1.2.4
later                               later    1.1.0.1
lazyeval                         lazyeval      0.2.2
leiden                             leiden      0.3.7
lifecycle                       lifecycle      1.0.0
limma                               limma     3.46.0
listenv                           listenv      0.8.0
lmtest                             lmtest     0.9-38
magrittr                         magrittr      2.0.1
markdown                         markdown        1.1
MatrixGenerics             MatrixGenerics      1.2.1
matrixStats                   matrixStats     0.58.0
memoise                           memoise      2.0.0
mime                                 mime       0.10
miniUI                             miniUI    0.1.1.1
mixtools                         mixtools      1.2.0
msigdbr                           msigdbr      7.2.1
munsell                           munsell      0.5.0
openssl                           openssl      1.4.3
parallelly                     parallelly     1.24.0
patchwork                       patchwork      1.1.1
pbapply                           pbapply      1.4-3
pillar                             pillar      1.6.0
pkgbuild                         pkgbuild      1.2.0
pkgconfig                       pkgconfig      2.0.3
pkgload                           pkgload      1.2.1
plogr                               plogr      0.2.0
plotly                             plotly      4.9.3
plyr                                 plyr      1.8.6
png                                   png      0.1-7
polyclip                         polyclip     1.10-0
praise                             praise      1.0.0
prettyunits                   prettyunits      1.1.1
processx                         processx      3.5.1
promises                         promises    1.2.0.1
ps                                     ps      1.6.0
purrr                               purrr      0.3.4
R.methodsS3                   R.methodsS3      1.8.1
R.oo                                 R.oo     1.24.0
R.utils                           R.utils     2.10.1
R6                                     R6      2.5.0
RANN                                 RANN      2.6.1
rappdirs                         rappdirs      0.3.3
rcmdcheck                       rcmdcheck      1.3.3
RColorBrewer                 RColorBrewer      1.1-2
Rcpp                                 Rcpp      1.0.6
RcppAnnoy                       RcppAnnoy     0.0.18
RcppArmadillo               RcppArmadillo 0.10.4.0.0
RcppEigen                       RcppEigen  0.3.3.9.1
RcppProgress                 RcppProgress      0.4.2
RCurl                               RCurl   1.98-1.3
rematch2                         rematch2      2.1.2
remotes                           remotes      2.3.0
reshape2                         reshape2      1.4.4
reticulate                     reticulate       1.18
rlang                               rlang     0.4.10
ROCR                                 ROCR     1.0-11
roxygen2                         roxygen2      7.1.1
rprojroot                       rprojroot      2.0.2
RSpectra                         RSpectra     0.16-0
RSQLite                           RSQLite      2.2.6
rstudioapi                     rstudioapi       0.13
Rtsne                               Rtsne       0.15
rversions                       rversions      2.0.2
S4Vectors                       S4Vectors     0.28.1
sass                                 sass      0.3.1
scales                             scales      1.1.1
scattermore                   scattermore        0.7
sctransform                   sctransform      0.3.2
segmented                       segmented      1.3-3
sessioninfo                   sessioninfo      1.1.1
Seurat                             Seurat      4.0.1
SeuratObject                 SeuratObject      4.0.0
shiny                               shiny      1.6.0
SingleCellExperiment SingleCellExperiment     1.12.0
sitmo                               sitmo      2.0.1
snow                                 snow      0.4-3
sourcetools                   sourcetools      0.1.7
spatstat.core               spatstat.core      2.0-0
spatstat.data               spatstat.data      2.1-0
spatstat.geom               spatstat.geom      2.1-0
spatstat.sparse           spatstat.sparse      2.0-0
spatstat.utils             spatstat.utils      2.1-0
stringi                           stringi      1.5.3
stringr                           stringr      1.4.0
SummarizedExperiment SummarizedExperiment     1.20.0
sys                                   sys        3.4
tensor                             tensor        1.5
testthat                         testthat      3.0.2
tibble                             tibble      3.1.1
tidyr                               tidyr      1.1.3
tidyselect                     tidyselect      1.1.0
usethis                           usethis      2.0.1
utf8                                 utf8      1.2.1
uwot                                 uwot     0.1.10
vctrs                               vctrs      0.3.7
viridisLite                   viridisLite      0.4.0
waldo                               waldo      0.2.5
whisker                           whisker        0.4
withr                               withr      2.4.1
xfun                                 xfun       0.22
XML                                   XML   3.99-0.6
xml2                                 xml2      1.3.2
xopen                               xopen      1.0.0
xtable                             xtable      1.8-4
XVector                           XVector     0.30.0
yaml                                 yaml      2.2.1
zip                                   zip      2.1.1
zlibbioc                         zlibbioc     1.36.0
zoo                                   zoo      1.8-9

**Comment by ncborcherding** [comment]
Hey Tom,

Thanks for reaching out.

Would you mind giving me the code you used to get the gene sets?

Thanks,
Nick

**Comment by tomthomas3000** [comment]
Dear Nick,

Thank you for your response!

I have essentially pseudobulked a single cell dataset  - I use it to create ‘gene scores’ it used to work really nicely using escape around 2-3 months ago!

Attached is the code I used.

Kind Regards,
Tom

From: theHumanBorch ***@***.***>
Date: Sunday, 18 April 2021 at 23:38
To: ncborcherding/escape ***@***.***>
Cc: Tom Thomas ***@***.***>, Author ***@***.***>
Subject: Re: [ncborcherding/escape] Error when running enrichIt (#20)

Hey Tom,

Thanks for reaching out.

Would you mind giving me the code you used to get the gene sets?

Thanks,
Nick

**Comment by ncborcherding** [comment]
Hey Tom,

I don't see the code attached. But what is likely the issue is that the gsva R package changed the way it handles gene sets. So you might need to update escape using the below code to get the most up-to-date version.

```
devtools::install_github("ncborcherding/escape")
```

Thanks,
Nick

**Comment by tomthomas3000** [comment]
Dear Nick,

Ah how strange – I can see the attachment in the sent section (might have been flagged by organisational firewalls potentially!). Please see below.

library(AUCell)
library(GSEABase)
library(escape)
library(GSVA)
library(SingleCellExperiment)
library(Seurat)

exprMatrix <- read.table("pseudocounts_sum.tsv", header = TRUE, row.names = 1)
exprMatrix <- as.matrix(exprMatrix)
dim(exprMatrix)

General <-c("ENSG00000111537","ENSG00000027697","ENSG00000159128","ENSG00000136634","ENSG00000168811","ENSG00000113302","ENSG00000096996","ENSG00000081985","ENSG00000169194","ENSG00000112115","ENSG00000112116","ENSG00000150782","ENSG00000115604","ENSG00000115607","ENSG00000115008","ENSG00000125538","ENSG00000109471","ENSG00000138684","ENSG00000103522","ENSG00000127318","ENSG00000110944","ENSG00000162594","ENSG00000147168","ENSG00000113520","ENSG00000077238","ENSG00000113525","ENSG00000136244","ENSG00000177606","ENSG00000109320","ENSG00000173039","ENSG00000069667","ENSG00000143365","ENSG00000143546","ENSG00000163220","ENSG00000115415","ENSG00000168610","ENSG00000138378","ENSG00000166888","ENSG00000105329","ENSG00000092969","ENSG00000119699","ENSG00000232810")


M4 <- c("ENSG00000122641","ENSG00000122691","ENSG00000158163","ENSG00000148848","ENSG00000085265","ENSG00000165886","ENSG00000133048","ENSG00000118985","ENSG00000225614","ENSG00000181458","ENSG00000159216","ENSG00000149305","ENSG00000162849","ENSG00000088882","ENSG00000114270","ENSG00000078098","ENSG00000108950","ENSG00000042062","ENSG00000186407","ENSG00000154096","ENSG00000101825","ENSG00000164932","ENSG00000138316","ENSG00000101236","ENSG00000102265","ENSG00000186393","ENSG00000133466","ENSG00000172817","ENSG00000164294","ENSG00000268734","ENSG00000095752","ENSG00000179431","ENSG00000102359","ENSG00000117122","ENSG00000137462","ENSG00000177464","ENSG00000136378","ENSG00000134013","ENSG00000151726","ENSG00000126785","ENSG00000118785","ENSG00000138448","ENSG00000183876","ENSG00000170458","ENSG00000110218")


M5 <- c("ENSG00000162747","ENSG00000163563","ENSG00000119535","ENSG00000140932","ENSG00000163735","ENSG00000163220","ENSG00000078081","ENSG00000143546","ENSG00000180871","ENSG00000068366","ENSG00000163464","ENSG00000124875","ENSG00000114251","ENSG00000103569","ENSG00000111536","ENSG00000116701","ENSG00000171051","ENSG00000163421","ENSG00000124731","ENSG00000163221","ENSG00000162493","ENSG00000182885","ENSG00000274536","ENSG00000086300","ENSG00000196611","ENSG00000181631","ENSG00000111199","ENSG00000270547","ENSG00000181104","ENSG00000224397","ENSG00000255398","ENSG00000099985","ENSG00000150551","ENSG00000008516","ENSG00000187116","ENSG00000170909","ENSG00000204577","ENSG00000149968","ENSG00000113749","ENSG00000163823","ENSG00000134571","ENSG00000171049","ENSG00000029153","ENSG00000136689","ENSG00000162551","ENSG00000182782","ENSG00000203747","ENSG00000101916","ENSG00000150681","ENSG00000151948","ENSG00000091106","ENSG00000239998","ENSG00000223749","ENSG00000150337","ENSG00000251230","ENSG00000120217","ENSG00000143226","ENSG00000131042","ENSG00000142748","ENSG00000105352","ENSG00000104974","ENSG00000105825","ENSG00000250548","ENSG00000188677","ENSG00000262406","ENSG00000244482")


GeneralSets <- GeneSet(General, setName="General")
M4Sets <- GeneSet(M4, setName="M4")
M5Sets <- GeneSet(M5, setName="M5")

GeneralScores <- enrichIt(obj = exprMatrix, gene.sets = GeneralSets, groups = 1000, cores = 1)
M4Scores <- enrichIt(obj = exprMatrix, gene.sets = M4Sets, groups = 1000, cores = 1)
M5Scores <- enrichIt(obj = exprMatrix, gene.sets = M5Sets, groups = 1000, cores = 1)

Thank you!

Kind Regards,
Tom
From: Tom Thomas ***@***.***>
Date: Sunday, 18 April 2021 at 23:55
To: ncborcherding/escape ***@***.***>, ncborcherding/escape ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [ncborcherding/escape] Error when running enrichIt (#20)
Dear Nick,

Thank you for your response!

I have essentially pseudobulked a single cell dataset  - I use it to create ‘gene scores’ it used to work really nicely using escape around 2-3 months ago!

Attached is the code I used.

Kind Regards,
Tom

From: theHumanBorch ***@***.***>
Date: Sunday, 18 April 2021 at 23:38
To: ncborcherding/escape ***@***.***>
Cc: Tom Thomas ***@***.***>, Author ***@***.***>
Subject: Re: [ncborcherding/escape] Error when running enrichIt (#20)

Hey Tom,

Thanks for reaching out.

Would you mind giving me the code you used to get the gene sets?

Thanks,
Nick

**Comment by ncborcherding** [comment]
Hey Tom,

Thanks for the follow-up. You are indeed running a newer version of gsva that has changed how it uses geneSets. I woulld try updating the escape package first and seeing if that fixes the problem.

Thanks,
Nick

**Comment by tomthomas3000** [comment]
Dear Nick,

Many thanks for your assistance with this.

Unfortunately, updating to the latest version of escape did not work.

M4Scores <- enrichIt(obj = exprMatrix, gene.sets = M4Sets, groups = 1000, cores = 1)

Upon running the above command, I got the following error.

[1] "Using sets of 1000 cells. Running 1 times."
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘gsva’ for signature ‘"matrix", "character"’

To try to circumvent this, I deleted R from my computer, including R packages etc.  I reinstalled R, and I just ran

devtools::install_github("ncborcherding/escape"). Unfortunately, this produced the same error.


Kind Regards,
Tom

From: theHumanBorch ***@***.***>
Date: Monday, 19 April 2021 at 12:40
To: ncborcherding/escape ***@***.***>
Cc: Tom Thomas ***@***.***>, Author ***@***.***>
Subject: Re: [ncborcherding/escape] Error when running enrichIt (#20)

Hey Tom,

I don't see the code attached. But what is likely the issue is that the gsva R package changed the way it handles gene sets. So you might need to update escape using the below code to get the most up-to-date version.

devtools::install_github("ncborcherding/escape")

Thanks,
Nick

**Comment by ncborcherding** [comment]
Hey Tom,

I was able to replicate the issue - it is indeed a result of how GSVA now handles GeneSets and GeneSetCollections. The update in escape does not fix the GeneSet functionally, but does extract the Gene IDs from GeneSetCollection. 

Which is to say, I got it to work with (with the addition of a GeneSetCollection() call):

```
General <-c("ENSG00000111537","ENSG00000027697","ENSG00000159128","ENSG00000136634","ENSG00000168811","ENSG00000113302","ENSG00000096996","ENSG00000081985","ENSG00000169194","ENSG00000112115","ENSG00000112116","ENSG00000150782","ENSG00000115604","ENSG00000115607","ENSG00000115008","ENSG00000125538","ENSG00000109471","ENSG00000138684","ENSG00000103522","ENSG00000127318","ENSG00000110944","ENSG00000162594","ENSG00000147168","ENSG00000113520","ENSG00000077238","ENSG00000113525","ENSG00000136244","ENSG00000177606","ENSG00000109320","ENSG00000173039","ENSG00000069667","ENSG00000143365","ENSG00000143546","ENSG00000163220","ENSG00000115415","ENSG00000168610","ENSG00000138378","ENSG00000166888","ENSG00000105329","ENSG00000092969","ENSG00000119699","ENSG00000232810")

GeneralSets <- GeneSetCollection(GeneSet(General, setName="General"))

GeneralScores <- enrichIt(obj = exprMatrix, gene.sets = GeneralSets, groups = 1000, cores = 1)
```

Sorry for the confusion and thank you for bearing with me as I troubleshooted.

Nick
