### ISSUE TITLE
Cannot install package through devtools::install_github

### ISSUE THREAD

**Issue by Lobbii** [ncborcherding/escape#26]
devtools::install_github("ncborcherding/escape")

* installing *source* package ‘escape’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Warning: replacing previous import ‘vctrs::data_frame’ by ‘tibble::data_frame’ when loading ‘dplyr’
Error: object ‘msigdbr_species’ is not exported by 'namespace:msigdbr'
Execution halted
ERROR: lazy loading failed for package ‘escape’

**Comment by ncborcherding** [comment]
Hey Lobbi, 

Thanks for reaching out - 

Would you mind giving me your ```sessionInfo()``` ?

My initial guess is that you'll need to update the msigdbr R package (but we can confirm with the sessionInfo). About 6-8 months ago, the authors of msigdbr change around their function calls - the current escape master repo has adjusted to these change. I see ‘msigdbr_species’ in my current version of msigdbr (v7.4.1).

Thanks,
Nick

**Comment by Lobbii** [comment]
Thanks, I can install escape after installing msigdbr package
