### ISSUE TITLE
All gene sets highly significant with "getSignificance"

### ISSUE THREAD

**Issue by ms-gx** [ncborcherding/escape#27]
I successfully run escape on my scRNA data. However, when checking for gene sets which are significant using `getSignificance` I get `p_adjust == 0` for all gene sets.

I tried ANOVA and linear.model, both report all highly significant. Also, I run it on different groupings, also did not change the outcome.

Do you have an idea what could be the problem?

**Comment by ncborcherding** [comment]
Hey Michael,

Thanks for reaching out. 

To the first problem of too many significant pathways - this is a problem I am actively working on. The real limit here is the sheer n size being used - I am implementing some different testing strategies that will be in the newer version and including a confidence interval for the null hypothesis, but for now I do not have a quick fix. 

In terms of the same results despite different groupings - do you mean that you have the exact same results despite different groups or that there are a lot of p_adjust = 0 despite groupings? If it is the former, please send (either here or in[ email me](mailto:ncborch@gmail.com) me your:

1. ```sessioninfo()```
2. The calls you are making with ```getSignificance()```
3. The ```head()``` of your results

**Comment by ms-gx** [comment]
Dear Nick

No it is the later (a lot of p_adjust = 0).

**Comment by ncborcherding** [comment]
Ok thanks, I will reach out when I have the significance testing updated in the dev version.

**Comment by ms-gx** [comment]
Great, thanks much! :)

**Comment by EAC-T** [comment]
Getting the same results. The package will become very solid  if you develop a robust statistical method. 
Keep it up!

**Comment by maxc2020** [comment]
Hi Nick,
Great package... much needed. I'm having the same issues with statistical testing, in that an inplausably high number of Gene Sets are coming back with p-values of 0. I had four "groups" and ran ANOVA.
Any updates on significance testing updates?
Thanks, Max

**Comment by ncborcherding** [comment]
Hey Maxc2020, 

I have introduced additional testing for 2 group comparisons (both Wilcoxon and logistic regression), but am still working on a solution for multiple comparisons. The issue is not an "implausible" number of gene sets with highly significant p-values, but rather the massive bias the n size of each group in the ANOVA comparison gives. I am in the process of update escape to send to bioconductor, I will put the multicomparison issue on the top of my to-do list and post here when I have something updated. 

Thanks,
Nick

**Comment by maxc2020** [comment]
Thanks! Max

**Comment by ncborcherding** [comment]
I've added Kruskal-Wallis test to the dev branch, it is still not perfect, but the rank-based approach is more robust than the ANOVA. I will keep working on it though!
