### ISSUE TITLE
Some genesets NES score correlate with nCount, nFeatures

### ISSUE THREAD

**Issue by CisnerosFernandez** [ncborcherding/escape#29]
Hello, 

Many thanks for your package, I wanted to ask some questions regarding the results. 

In my dataset it looks like some of the genesets score present a very strong correlation with the number of features detected per cell or the number of counts (I attached some examples below). 

Thus, I would like to ask if you have encountered such an issue before? And if so, how did you handled it?

Thank you very much, 

Andrés 

Brief description of what I did in case it is useful: 

I processed the datasets with Seurat standard protocol and use the resulting object as input in the enrichIt function with the H library. Then added the ES resulting object to the metadata of the seurat object as per tutorial instructions. To obtain the correlation with the nFeature_RNA I used the FeatureScatter function of Seurat.

Examples:

![image](https://user-images.githubusercontent.com/82618802/128880899-51721058-4eba-4bc4-b977-072255fd61e5.png)
![image](https://user-images.githubusercontent.com/82618802/128881018-6d4ea6aa-42b7-4370-b625-55a81d651d19.png)
![image](https://user-images.githubusercontent.com/82618802/128881190-2208e70e-7e84-47e0-8ddf-a9cd435b7a0e.png)

**Comment by ncborcherding** [comment]
Hey CisnerosFernandez,

Thanks for reaching out and the pointing out the interesting problem. You are right - there must be something to do with "inflation" of the normalized enrichment score as cells decrease in number of features. 

By chance did you see this across other gene sets or just the gene sets you mentioned?

I will have to think about this some - what is the best way to weight the enrichment scores...hmm.

Thanks for reaching out and pointing out the problem!

Nick

**Comment by ncborcherding** [comment]
Hey CisnerosFernandez, 

I have added a new weight to the ```enrichIt()``` function in the dev branch - with the parameter **weight.by.nFeatures = TRUE**. This should prevent the trend you are seeing. 

You can try it out, by 

```
devtools::install_github("ncborcherding/escape")
```

I would be happy to hear if it works for you, from my end, I was saw a reduction in the "inflation".

**Comment by CisnerosFernandez** [comment]
Hello, 

Thank you very much, I will try it as soon as I resources available and will answer you back. 

Also I would like to apologize for not answering your first message, I missed the first notification of github on my mail. Now it is too late but the answer to your first question was that I saw it in some more genesets than the ones that I put as example but it not happened on all of them. 

Thanks again, 

Andrés

**Comment by CisnerosFernandez** [comment]
Hello, 

I ran the code with a subset of the cells, it seems that for some genesets it work but unfortunately others seem to still present some kind of "inflation". To install the developmental version I added @dev to devtools::install_github("ncborcherding/escape").

Thank you very much, 

Andrés 

![image](https://user-images.githubusercontent.com/82618802/129818651-6499a7d7-90ae-40e5-a53a-57bdbd6dd677.png)

![image](https://user-images.githubusercontent.com/82618802/129818708-f5c8a5c3-72c6-4ea2-9cec-e0c3ff853fb9.png)

![image](https://user-images.githubusercontent.com/82618802/129819471-8a33af75-5b38-483c-a79e-3436dc2d40ef.png)

**Comment by ncborcherding** [comment]
Hey Andrés,

Absolutely no problem on delayed reply! I appreciate all the info and comparison with before and after. 

Looks like I will need to investigate further on what is going on, the U-shape to the apoptosis, looks like the over-correction and obviously the others look like no correction occurred. 

I am going to re-open this issue. In the mean time, I did add 2 new methods of enrichment - Ucell and singscore to the developmental version, which might be worth [checking out](https://ncborcherding.github.io/vignettes/escape_vignette.html#4_Enrichment). 

Thanks again,
Nick

**Comment by ncborcherding** [comment]
Hey Andrés,

So I have been systematically looking at a number of gene sets across multiple data sets. I have even generating a single-cell data set with a bias towards features/enrichment correlation. Although I have found some correlation with specific gene sets. I have yet to recreate the high correlations value > 0.9 that you are reporting. I have removed the normalization by feature parameter.

For example - here are the plots of hypoxia (gene set built into escape) using a [ccRCC cohort](https://github.com/ncborcherding/ccRCC).

> **method = "UCell"**
> [Hypoxia_Ucell.pdf](https://github.com/ncborcherding/escape/files/7086279/Hypoxia_Ucell.pdf)
> 
> **method = "ssGSEA"**
> [Hypoxia_ssGSEA.pdf](https://github.com/ncborcherding/escape/files/7086280/Hypoxia_ssGSEA.pdf)

Would you mind maybe [emailing me](mailto:ncborch@gmail.com) more information about your project?
