### ISSUE TITLE
Error in running enrichIt

### ISSUE THREAD

**Issue by HocheolJang426** [ncborcherding/escape#36]
Hi
I'm tryinh enrichIt package with my seurat data

When I'm running the code;
gene.sets <- getGeneSets(library = "H")
ES <- enrichIt(obj = CD4T_naive, gene.sets = gene.sets, groups = 1000, cores = 4)

Error message repeat
[1] "Using sets of 1000 cells. Running 51 times."
Setting parallel calculations through a SnowParam back-end
with workers=4 and tasks=100.
Estimating ssGSEA scores for 50 gene sets.
Error in names(res)[compute_element] <- nms : replacement has length zero

Why dose this message repeat? Is this message mean there are no enriched geneset in my data?
I'm using escape version 1.3.1

**Comment by ncborcherding** [comment]
Hey Hocheol, 

This is an error with the handling of the parallel process and is stemming from the BiocParallel package - I would try re-installing or updating this package, restarting your R session, and trying the code again. 

Let me know if that doesn't work and we can go from there.

Nick

**Comment by HocheolJang426** [comment]
I updated BiocParallel, but another error comes

 ES2 <- enrichIt(obj = CD4T_naive, gene.sets = list, groups = 1000, cores = 4)
[1] "Using sets of 1000 cells. Running 51 times."
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘gsva’ for signature ‘"matrix", "function"’

Then, How can I solve this problem?

**Comment by ncborcherding** [comment]
Hey Hocheol,

The error is coming from **gsva** and it seems to me there might be an error in the gene.sets you are providing, can you show me how you are forming your gene sets?

Thanks,
Nick

**Comment by HocheolJang426** [comment]
ncborcherding,

I solved all the problem I suffered
Thanks for your kindness,
