### ISSUE TITLE
Question regarding enrichIt 

### ISSUE THREAD

**Issue by rythi4** [ncborcherding/escape#38]
I have a question regarding the output of enrichIt(). This type of analysis is new to me, so maybe the question is quite simple:
I tried to run enrichIt on a seurat object (13 clusters) with two genesets and then afterwards with only one of the gene sets. When I look at the enrichment scores for the geneset I tried twice, they are not the same (although the overall picture is the same), and I am not sure why? 
Does some sort of normalization over the genesets take place when running enrichIt() and can it explain the difference I see?

**Comment by rythi4** [comment]
Here is an example:

`
#Making GeneSetCollections:
set1 <- GeneSetCollection(GeneSet(genes[["X"]][["gene"]], setName = "x"), GeneSet(genes[["Y"]][["gene"]], setName = "y"), GeneSet(genes[["Z"]][["gene"]], setName = "z"), GeneSet(genes[["W"]][["gene"]], setName = "w"))
set2 <- GeneSetCollection(GeneSet(genes[["X"]][["gene"]], setName = "x"), GeneSet(genes[["Y"]][["gene"]], setName = "y"))

#Here I define the seurat_object: seurat_object <- XXX
DefaultAssay(seurat_object) <- "RNA"
seurat_object_1 <- UpdateSeuratObject(seurat_object)
ES.seurat_1 <- enrichIt(obj = seurat_object_1, gene.sets = set1, groups = 1000)
#Here I define the seurat_object: seurat_object <- XXX
DefaultAssay(seurat_object) <- "RNA"
seurat_object_1 <- UpdateSeuratObject(seurat_object)
ES.seurat_2 <- enrichIt(obj = seurat_object_1, gene.sets = set2, groups = 1000)
`
The two seurat_objects are defined by the exact same line of code. 

When I look at ES.seurat_1 and ES.seurat_2 (I order the columns 'x' by highest value for easy comparison), I see that the highest value is not the same:
![image](https://user-images.githubusercontent.com/92912238/149546706-72e756d0-b315-41da-becf-6b72d1e6ec90.png)

**Comment by ncborcherding** [comment]
Thank you so much for the reproducible example!! 

I found the issue - it lies in the GSVA package itself
<img width="513" alt="Screen Shot 2022-01-18 at 12 40 06 PM" src="https://user-images.githubusercontent.com/22754118/149998812-c111e5f9-967d-4408-b7b3-c78d681dc440.png">

I think this might be an error in my reading of the original manuscript for ssGSEA. I will take a look, I might have to implement an intrinsic normalization so the enrichment scores are deterministic. I'll post here when I get something working. 

Thanks for bringing this to my attention.

Nick

**Comment by rythi4** [comment]
Of course, that was no problem!

**Comment by ncborcherding** [comment]
The newest dev version (v1.3.5) now has a new parameter **ssGSEA.norm** which will scale the columns from 0 to 1. However, if you would like to subset the data at a later time, the default setting is now not to normalize the data. 

```
enrichIt <- function(obj, gene.sets = NULL, 
                     method = "ssGSEA", 
                     groups = 1000, 
                     cores = 2,
                     min.size = 5,
                     ssGSEA.norm = FALSE) 
```

Thanks again for letting me know about this. 

Nick
