### ISSUE TITLE
Available categories in GetGeneSets

### ISSUE THREAD

**Issue by linanzhang** [ncborcherding/escape#39]
Hello, I wasing wondering how to get gene sets other than H, C1, C2, .... 

I'm interesetd in REACTOME subset of CP. What should be the input?

Thank you.

**Comment by ncborcherding** [comment]
Hey Linanzhang, 

Thanks for reaching out.

in ```getGeneSets()```, there is a **subcategory** parameter that should allow you to do just that. 

Nick

**Comment by linanzhang** [comment]
Hello Nick, 

Thank you for your response. Could you please be more specific? I've tried commands like

`genesets <- getGeneSets(library = 'CP', subcategory = 'REACTOME')`

and got the following error message:

> Error in getGeneSets(library = "CP", subcategory = "REACTOME") : 
>   unused argument (subcategory = "REACTOME")

and 

`genesets <- getGeneSets(library = 'CP')`

with error message:

> Error in msigdbr(species = spec_check, category = library) : 
>   unknown category

**Comment by ncborcherding** [comment]
Hey Linanzhang, 

Sorry, should have included the exact code and mentioned this is in the dev version on the github repo - my mistake. 

```
devtools::install_github("ncborcherding/escape@dev")
GS <- getGeneSets(library = "C2", subcategory = "CP:REACTOME")
```

Nick
