### ISSUE TITLE
Calculating average ssGSEA score for easy-to-see heatmap?

### ISSUE THREAD

**Issue by SimoniMD** [ncborcherding/escape#47]
Hi!

I'm  working on some pathway heatmaps, and have gotten up to this:
![M pathways heatmap percond](https://user-images.githubusercontent.com/82599359/158189754-db426c8d-7404-46a1-b581-a4796fce2433.png)

I know the best part about scRNA is the ability to see things on the single-cell level, but is there a way to display the scoring data from each cluster an an average? so it's not individual ticks for each cell and rather just one color for the average of the cluster? (or any other suggestions for visualization -  as you can see, i turned down the colors to 10 to see the differences a little better)

I'm looking for something along the lines of the the `AverageExpression()` function in Seurat that allows  one to create a heatmap like below:
![mono marker_heatmap](https://user-images.githubusercontent.com/82599359/158190204-3c4a726e-b858-4947-89c4-414a928535ea.png)

Thanks!

**Comment by ncborcherding** [comment]
Hey SimoniMD,

This is a good suggestion and actually the way I generally summarise my enrichment results - I will add it to the to do list and have it released in the next version. 

In the interim, a method for this using tidyr would be:

```
seuratObj <- addMetaData(seuratObj, ES)
seurat.meta <- seuratObj@meta.data
summary <- seurat.meta %>%
                            group_by(variable) %>%
                            summarise(across(colnames(ES), median))
#You can make this ggplot friendly with
summary.melt <- reshape2::melt(summary)
```

Thanks,
Nick

**Comment by Dragonmasterx87** [comment]
Hi @ncborcherding ,

Sorry for the stupid question, but I havent gotten this to work. 
If I have a seurat object called `data` and an erichIT obj called `ES` where I have performed the following:

```
seurat.meta <- data$meta.data
summary <- seurat.meta %>%
  group_by("celltype") %>% #celltype being the slot of metadata I would want to create averages for
  summarise(across(colnames(ES), median))
summary.melt <- reshape2::melt(summary)
```

The output doesnt make sense, its just some median value of all cells, not seggregated data based on a meta data slot i.e. celltype. If we dont do this somehow we wont be able to plot an average heatmap of certain strings of GO types..... any suggestions?

The goal is to make a heatmap possibly using ditto similar to what we do natively for all cells, but showing averages instead of all cell values.

Cheers and thanks again!
🐲

**Comment by Dragonmasterx87** [comment]
For now this is what im doing....lol....But I think the heatmaps would be great to use as well.

![image](https://user-images.githubusercontent.com/39837140/221380757-359b02fa-17b0-4f24-9b5e-3145a294b06b.png)

**Comment by Dragonmasterx87** [comment]
For now this is what im doing....would be gerat to have the heatmap function work as well!!!

![image](https://user-images.githubusercontent.com/39837140/221380788-fd096e29-3caa-444a-bc86-34bf69308a89.png)

**Comment by ncborcherding** [comment]
Hey @Dragonmasterx87 

I think you might have an error in your tidy grammar - instead of **"celltype"**, it should be **celltype** with no quotes. With quotes, it ends up summarizing across all cells instead of looking for a variable. 

So it should read like this:
```
seurat.meta <- data$meta.data
summary <- seurat.meta %>%
  group_by(celltype) %>% #here is the change
  summarise(across(colnames(ES), median))
summary.melt <- reshape2::melt(summary)
```

Hope that helps,
Nick
