### ISSUE TITLE
plotpathway() : sort by seurat clusters? Also, can I just keep the violin plot, but not the individual dots. 

### ISSUE THREAD

**Issue by rpauly** [ncborcherding/escape#48]
Hi,
Is there a way to sort by seurat clusters? Also, can I plot he boxplot with no individual dots?
Current command:
`plotPathway(sce_rp, resultName = "VAM_H_CDF", geneset = hallmark, groupby = "seurat_clusters", boxplot=TRUE)`

Thanks,
Rini

**Comment by ncborcherding** [comment]
Hey Rini, 

Thanks for reaching out.

Could you give me more information on the version and what you are trying to do?

```plotPathway()``` is not a function in escape - is there another package you are using?

Thanks,
Nick
