### ISSUE TITLE
Subsetting objects by cluster for visualization

### ISSUE THREAD

**Issue by wht10** [ncborcherding/escape#51]
Hey Nick, 

Thank you so much for your contributions to the single-cell analysis field. 

Sometimes when I am making visualizations from a Seurat object, I only want to focus on a subset of clusters. 

I have been doing this by subsetting the whole object, while passing it to a visualization function. 

```r
dittoHeatmap(subset(seurat_ex, idents = c("C1","C2")),
 genes = NULL, metas = names(ES),
             heatmap.colors = rev(colorblind_vector(50)),
             annot.by = c("active.idents", "Type"),
             cluster_cols = TRUE,
             fontsize = 7)
```

The visualizations using the `ES2` object can be subset the following way too.

```r
ridgeEnrichment(ES2[ES2$cluster %in% c("C1","C2")], gene.set = "HALLMARK_DNA_REPAIR", 
group = "cluster", facet = "Type", add.rug = TRUE)
```

Anyway, I thought this was an interesting additional functionality in case you wanted to add this to the vignette for anyone else that might want to focus in on subsets of clusters, as it is something that isn't very clear on how to do in Seurat or the dittoSeq vignettes.

**Comment by ncborcherding** [comment]
Hey Billy, 

Thanks for reaching out and the suggestion, I will add your approach to the vignette in the next commit! Let me know if you have any other suggestions.

Nick
