### ISSUE TITLE
I have problem with the format of my input data 

### ISSUE THREAD

**Issue by pariaaliour** [ncborcherding/escape#52]
I'm trying to run the code as below
suppressPackageStartupMessages(library(escape))
> suppressPackageStartupMessages(library(dittoSeq))
> suppressPackageStartupMessages(library(SingleCellExperiment))
> suppressPackageStartupMessages(library(Seurat))
> suppressPackageStartupMessages(library(SeuratObject))
als <- readRDS("/home/paria/scratch/als-project/analysis/OCU_MED/clustering/new/full_sample_k_100_resolution_0.8_PC_50.rds")
als <- DietSeurat(suppressMessages(UpdateSeuratObject(als)))
Error in slot(object = object, name = x) : 
  no slot of name "median_umi" for this object of class "SCTModel"

I was trying to extract the count matrix from Seurat object but I'm still getting the same error. Not sure were I'm doing it wrong or do I actually need two have median umi or it is not necessary. The ALS object is as below
als
An object of class Seurat 
63224 features across 92297 samples within 3 assays 
Active assay: SCT (30612 features, 3000 variable features)
 2 other assays present: RNA, integrated
 1 dimensional reduction calculated: pca

I really appreciate if you let me know how I can solve it? By using count matrix only? if yes what is the best way of extracting it?
Thanks,
Paria

**Comment by ncborcherding** [comment]
Hey Pariaaliour, 

Thanks for reaching out - this seems to be an error with the Seurat package itself (likely ```DietSeurat()``` is not compatible with SCT)

However this doesn't matter - ```enrichIt()``` only works with RNA count info, do you could skip the ```DietSeurat()``` step and go straight to ```enrichIt()```

If you want to just extract the count matrix: 

```
exp.matrix <- als@assays[["RNA"]]@counts
```

Let me know if you have any questions. 

Nick

**Comment by pariaaliour** [comment]
Hi Nick,
Thanks for your response!
So, I did the below command and got the error 
> GS <- list(Glutamatergic = c("SV2B","SATB2","CELF2","PHACTR1","CHN1","KHDRBS3","RALYL", "LDB2","NELL2","KALRN"), GABAergic = c("GAD1","GRIP1","KAZN","KCNC2","TCF4","GAD2","MAF","SLC6A1","RBMS3","NHS"), NonNeuronal = c("QKI","ZBTB20","NCKAP5","PTGDS","PHLPP1","CDH20","PPP2R2B","PDE4B","DOCK1","MAP4K4"))
exp.matrix <- als@assays[["RNA"]]@counts
ES.seurat <- enrichIt(obj = exp.matrix, gene.sets = GS, groups = 56000)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': 'x' must be an array of at least two dimensions
Do you know what is this error for?

**Comment by ncborcherding** [comment]
Hey pariaaliour, 

Does what does ```dim(exp.matrix)```?

Also what version of escape are you using?

Thanks,
Nick

**Comment by pariaaliour** [comment]
It's 
dim(GS)
NULL
and the version I use is 1.4.0

**Comment by ncborcherding** [comment]
Hey pariaaliour,

Is the object you create with ```exp.matrix <- als@assays[["RNA"]]@counts``` NULL? That would be the cause of that error.

Nick

**Comment by pariaaliour** [comment]
It is not NULL. when I do exp.matrix(dim) its returns 30612 92297.

**Comment by ncborcherding** [comment]
Just to clarify because there have been some formatting issues above - the following code:

```
exp.matrix <- als@assays[["RNA"]]@counts
ES.seurat <- enrichIt(obj = exp.matrix, gene.sets = GS, groups = 56000)
```

results in this error:

> Error in h(simpleError(msg, call)) :
error in evaluating the argument 'i' in selecting a method for function '[': 'x' must be an array of at least two dimensions

If so, what is the output of:

```
head(exp.matrix@x)
```

**Comment by pariaaliour** [comment]
head(exp.matrix@x)
[1] 2 2 1 1 1 1

**Comment by ncborcherding** [comment]
Also - does this give you the error you mention above:

```
exp.matrix <- als@assays[["RNA"]]@counts
ES.seurat <- enrichIt(obj = exp.matrix, gene.sets = GS, groups = 56000)
```

**Comment by pariaaliour** [comment]
yes, the below error:
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': 'x' must be an array of at least two dimensions
I'm thinking this could be bc GS(dim) return NULL. But I'm exactly following what is in tutorial.

**Comment by ncborcherding** [comment]
Hey Pariaaliour,

## Just to clarify: 
```GS(dim)``` should give you the error **Error in GS(dim) : could not find function "GS"**
```dim(GS)``` should give you NULL - ```dim()``` works on vectors, youd have to use it on individual elements of your list to get anything back

The following produces a sparse matric of dimensions: 30612 92297. This sparse matrix has 2 dimensions and values (```exp.matrix$x```)
```
als <- readRDS("/home/paria/scratch/als-project/analysis/OCU_MED/clustering/new/full_sample_k_100_resolution_0.8_PC_50.rds")
exp.matrix <- als@assays[["RNA"]]@counts
```

But you are still getting this error:

> Error in h(simpleError(msg, call)) :
error in evaluating the argument 'i' in selecting a method for function '[': 'x' must be an array of at least two dimensions

## Have you tried just using: 

```
#Load Seurat Object
als <- readRDS("/home/paria/scratch/als-project/analysis/OCU_MED/clustering/new/full_sample_k_100_resolution_0.8_PC_50.rds")

#Set Gene Sets
GS <- list(Glutamatergic = c("SV2B","SATB2","CELF2","PHACTR1","CHN1","KHDRBS3","RALYL", "LDB2","NELL2","KALRN"), GABAergic = c("GAD1","GRIP1","KAZN","KCNC2","TCF4","GAD2","MAF","SLC6A1","RBMS3","NHS"), NonNeuronal = c("QKI","ZBTB20","NCKAP5","PTGDS","PHLPP1","CDH20","PPP2R2B","PDE4B","DOCK1","MAP4K4"))

#Calculate Enrichment
ES.seurat <- enrichIt(obj = exp.matrix, gene.sets = GS, groups = 56000) #I'd lower the groups back to 1000-5000 to save on memory

## If this does not work:

Would you mind [emailing me](mailto:ncborch@gmail.com) your exp.matrix object or Seurat object as an rds or something just so I can take a look? This really shouldn't be an issue and I do not see how the data is not structured properly to work with the ```enrichIt()``` function

**Comment by pariaaliour** [comment]
I'm getting the same error. I'm sending you my .rds file. 
Thank you so much!

**Comment by ncborcherding** [comment]
Hey Pariaaliour,

I have no issues running the following code using your rds object you sent (thanks a lot). 

```
library(Seurat)
library(escape)
als <- readRDS("~/Downloads/full_sample_k_100_resolution_0.8_PC_50(1).rds")

GS <- list(Glutamatergic = c("SV2B","SATB2","CELF2","PHACTR1","CHN1","KHDRBS3","RALYL", "LDB2","NELL2","KALRN"), 
           GABAergic = c("GAD1","GRIP1","KAZN","KCNC2","TCF4","GAD2","MAF","SLC6A1","RBMS3","NHS"), 
           NonNeuronal = c("QKI","ZBTB20","NCKAP5","PTGDS","PHLPP1","CDH20","PPP2R2B","PDE4B","DOCK1","MAP4K4"))

#Calling the data from seurat
ES.seurat <- enrichIt(obj = als, gene.sets = GS, groups = 56000)

#Making a sparse matrix first
exp.matrix <- als@assays[["RNA"]]@counts
ES.seurat <- enrichIt(obj = exp.matrix, gene.sets = GS)
```

This is using the current master github version (1.4.1) - you can install this with:

**Comment by pariaaliour** [comment]
I installed the newer version and it worked. I really appreciate it.
Thanks a ton!
