### ISSUE TITLE
Contour lines on tSNE/UMAP

### ISSUE THREAD

**Issue by s849** [ncborcherding/escape#53]
Hi,

Thank you for developing Escape! I am using it for ssGSEA analysis. But I also am interested in adding contour plots to tSNE/UMAP embedding similarly as in figure 1b in your Communications Biology manuscript (congratulations btw, very nice paper!) I am interested in adding contour lines to highlight 1) cell density on a cluster basis (i.e., add a contour on cluster X) and 2) add a contour on cells expressing gene Y (to discriminate between clusters of cells expressing gene Y vs. those that do not).

Do you have any examples of how to do this? Would really appreciate it!

Thank you!

**Comment by ncborcherding** [comment]
Hey s849, 

Thanks for reaching out - all the code for the manuscript is available [here](https://github.com/ncborcherding/ccRCC). Specifically, the contour plot code is available [here ](https://github.com/ncborcherding/ccRCC/blob/master/Integration.Rmd) starting on line 162.

In terms of making a gene-expression-based plot - you could probably use the same code after add a variable for the gene in the meta data. 

I am going to close this issue as it is not an issue with the package - but feel free to follow up with questions if you have any.

Nick
