### ISSUE TITLE
Visualization of Enrichment

### ISSUE THREAD

**Issue by brookeabrown** [ncborcherding/escape#54]
Hello,

Thank you for this package and the vignette - they are extremely helpful!

I was curious if there is a way to visualize the enrichment results as a dot plot as with ClusterProfiler?(https://datascience.bioturing.com/app/repo/how-to-do-gene-set-enrichment-analysis-using-clusterprofiler-b6643ddde97f4896882d6e16565045ac/v1.0.3-rc1)
I have two groups that I want to know what KEGG and Hallmark pathways are differentially enriched between the clusters. 

Thank you,
Brooke

![image](https://user-images.githubusercontent.com/105321750/173433267-146e7da3-8f36-41d2-83a3-ef69273e3add.png)

**Comment by ncborcherding** [comment]
Hey Brooke, 

Thanks for reaching out!

The enrichment calculation performed in escape (either ssGSEA or UCell) is different than the underlying calculation using ClusterProfiler. The latter is taking the differential gene expression list between groups (most often clusters) and performing traditional GSEA using hypergeometric testing of the rank list (outputs a NES, gene ratio, p-value,etc). escape is using the per cell expression values to generate an enrichment score for each cell - this prevents the calculation of gene ratios. There is a ```getSignificance()``` function in escape that will give you several options for calculating a p-value after performing the enrichment for each cell. 

Sorry there isn't a better option, but I'll keep thinking of a way to show something similar. 

Nick
