### ISSUE TITLE
Improve computational time for EnrichIt(), performPCA(), and masterPCAplot

### ISSUE THREAD

**Issue by monikaramos** [ncborcherding/escape#55]
Hi there! Great package, I am a huge fan!

I am wondering if there is a way to improve the computational time it takes to run the functions performPCA(), and masterPCAplot when considering larger gene sets such as MsigDB's curated gene set C2 that has ~6000+ gene sets to do GSEA on. For example, it took 8 hours to finish running just performPCA(). Is there an ability to specify or increase the multi-core processors or threads?

Thanks!

**Comment by ncborcherding** [comment]
Hey Monikaramos,

There are several faster PCA options, see [here](https://www.rdocumentation.org/packages/gmodels/versions/2.18.1.1/topics/fast.prcomp) or [here](https://rdrr.io/cran/Morpho/man/prcompfast.html). There are also packages for PCA in the context of large data - see [here](https://rdrr.io/cran/bigpca/man/bigpca-package.html). 

I will put this on "to-do" list, thanks for the suggestion. 

Nick
