### ISSUE TITLE
Median of getSignificance and multi_dittoPlot() don't match

### ISSUE THREAD

**Issue by cr2106** [ncborcherding/escape#56]
Hey Nick,

I am testing escape, and I love it! I want to convert the previous analysis I did with the module score from Seurat and use the enrichment analysis from escape instead.

I have a problem, and I'm not sure what the cause is. In short, I used enrichIt() on a gene set and getSignificance().
When I plotted with multi_dittoPlot() (but the same happens if I use geom_violin() and geom_boxplot()  ), the median of the three groups doesn't match the median calculated by getSignificance():

<img width="304" alt="Screenshot 2022-08-19 at 19 03 37" src="https://user-images.githubusercontent.com/85880451/185671004-eba40fb8-d7c1-4264-a9e1-4188fb57304a.png">

<img width="589" alt="Screenshot 2022-08-19 at 19 05 32" src="https://user-images.githubusercontent.com/85880451/185671024-d822ddd2-fb96-48ec-8c42-3920e9d26f58.png">

The group "M" should have the lowest median (0.44), while "S" has the highest (0.47). However, from the plot M is higher than S.

getSignificance() also replicated what I observed before with Seurat module score. This also happens with other gene sets, so I am puzzled.

I really appreciate any help you can provide.

**Comment by ncborcherding** [comment]
Hey CR2106, 

Thanks for the excellent run down of the issue. You are completely correct there is something fishy/bug going on. It was in the function that calculates the median values not using the group_by variable as the final column name. I just wrote and test the fix for it and it is up in the dev version of escape:

```
devtools::install_github("ncborcherding/escape@dev")
```

Thanks,
Nick

**Comment by cr2106** [comment]
Thank you! Now it works
