### ISSUE TITLE
masterPCAplot bug

### ISSUE THREAD

**Issue by JLTrincado** [ncborcherding/escape#57]
Just a small bug. It seems variable top.contribution in masterPCAplot is not used inside the function. Modify 

`  
names <- tbl %>% top_n(n = 10, (factors.x + factors.y)/2)
` 
by 
`  
names <- tbl %>% top_n(n = top.contribution, (factors.x + factors.y)/2)
`

Thanks for your amazing work.

Best,
JL

**Comment by ncborcherding** [comment]
Hey Juan, 

Thanks for letting me know! Made the commit to the dev branch (also changed the ```top_n()``` call to ```slice_max()``` as I think top_n is being deprecated). 

Thanks again,
Nick
