### ISSUE TITLE
enrichIT values-negative scores

### ISSUE THREAD

**Issue by samyuktha-suresh** [ncborcherding/escape#60]
Hello!
I am new to this package and comp biology in general and was just applying the enrichIT code that was published in a paper on my dataset. Turns out that most of the enrichIT values for the geneset I used from the paper on my single cell data were negative. I just wanted to check if I interpret it as downregulation of this geneset in my data. 
Thanks!
Sam

**Comment by ncborcherding** [comment]
Hey @samyuktha-suresh, 

Thanks for reaching out - don't know the version you are using, but the old version of escape used a min-max normalization across all of the gene sets and cells. This can create negative values, but shouldn't be all/mostly negative unless you have an extreme outlier. 

The newer versions of escape allow for you to return normalized enrichment scores by default or if ```ssGSEA.norm = TRUE``` will return min-max normalized values for each gene set (so all the values will be between 0 and 1). 

I am assuming you are using the older version - maybe try updating via the repo and try your results then?

Nick

**Comment by samyuktha-suresh** [comment]
Hello @ncborcherding 
Thanks a lot for your suggestion. I am using the version 1.5.1, which is a pretty new version if I am not mistaken, so not sure why there was no normalization done. But the <ssGSEA.norm= T> did of course work as said. 
Thanks!
Sam

**Comment by ncborcherding** [comment]
Good to hear and thanks for the follow up!
