### ISSUE TITLE
Differentially expressed genes in enrichment pathways

### ISSUE THREAD

**Issue by YKH810325** [ncborcherding/escape#62]
Dear developer,

This software is so powerful and useful to annotate cell functions.
However, I would like to understand whether this software can further identify differentially expressed genes in certain enriched pathways.
Thank you so much!

Sincerely

YK

**Comment by ncborcherding** [comment]
Hey YK, 

Thanks for reaching out and the kind words!

There is not yet anything built in to the package that teases apart the underlying expression differences leading to differential enrichment (something like leading edge analysis in the traditional GSEA). Is that what you were thinking? Or do you have any suggestions? I've been working on updating the package and would be happy to incorporate. 

Thanks,
Nick

**Comment by ncborcherding** [comment]
I'm going to close this due to lack of info - feel free to provide info below.

**Comment by YKH810325** [comment]
Dear Nick,
Sorry for late reply.
When we perform GSEA to analyze the RNA-seq data, they will give us enriched set figure with leading edge and also heatmap with differentially expressed genes (DEGs) in certain significant pathway.
It is great if we can also observe enriched set figure and corresponding DEGs in certain significant pathway of scRNA-seq dataset.

Thanks,
YK
