### ISSUE TITLE
about using a subset of groups in visualization

### ISSUE THREAD

**Issue by Pedramto89** [ncborcherding/escape#64]
Hi. I am using Visium data to do the ssGSEA. I followed the tutorial but when it comes to creating the heatmap, I cannot do it only for a limited number of groups which is here my clusters:
`dittoHeatmap(obj, genes = NULL, metas = names(ES.seurat), 
             annot.by = "seurat_clusters", 
             fontsize = 7, 
             cluster_cols = TRUE,
             heatmap.colors = colors(50))`
By the above command, I get the heatmap for all clusters; however, I want to do it only for example a couple of them. 
Do you have any idea how can I get the clusters of interest?
![Rplot](https://user-images.githubusercontent.com/85902042/219154303-7dcfef4d-56b3-4a83-8957-b51ec01388a8.png)

**Comment by ncborcherding** [comment]
Hey Pedram, 

Thanks for reaching out, you should be able to subset the heatmap using the **idents** parameter in the ```dittoHeatmap()``` function from dittoseq. 

Check out more at #51 

Thanks,
Nick

**Comment by Pedramto89** [comment]
Thank you @ncborcherding for your prompt response!
So, I tried this but did not work:
`dittoHeatmap(obj, genes = NULL, metas = names(ES.seurat), 
             annot.by = "seurat_clusters", 
             fontsize = 7, (Idents(obj)<- c(8,9),
             cluster_cols = TRUE,
             heatmap.colors = colors(50))`

But did not work. As it appears on the heatmap, I have 10 clusters ranging from 0 to 9. And I want to see some enrichments in some of them.

**Comment by ncborcherding** [comment]
Hey Pedram, 

Think there might be an issue with how you are calling things, try: 

```
dittoHeatmap(obj, genes = NULL, metas = names(ES.seurat),  
              annot.by = "seurat_clusters",  fontsize = 7,  
              Idents = c(8,9), cluster_cols = TRUE,  #here is the change
              heatmap.colors = colors(50))
```

Nick

**Comment by Pedramto89** [comment]
Hi @ncborcherding 
Thank you! 
It did not work too!
I also tried this but could not get the clusters of interest, did not show any error though!
`dittoHeatmap(obj, genes = NULL, metas = names(ES.seurat),  
             annot.by = "seurat_clusters",  fontsize = 7,  
             Idents = c("1","9"), cluster_cols = TRUE,  #here is the change
             heatmap.colors = colors(50))`

This is the image I still get after running the code:


<img width="1082" alt="image" src="https://user-images.githubusercontent.com/85902042/219454502-686a967c-b554-4582-8b4c-a2173c891a32.png">

**Comment by ncborcherding** [comment]
Did you get an error with the following code?

```
dittoHeatmap(obj, genes = NULL, metas = names(ES.seurat),  
              annot.by = "seurat_clusters",  fontsize = 7,  
              idents = c(8,9), cluster_cols = TRUE,  #modified this line, accidentally capitalized idents.
              heatmap.colors = colors(50))
```

**Comment by Pedramto89** [comment]
Hi @ncborcherding 
Thank you! 
No, I get no error but it shows all the 10 clusters rather than the specified ones in the "idents". The same as the above image I sent. It seems it doesn't specify the clusters when we use "idents".

**Comment by ncborcherding** [comment]
Hey Pedram - 

It might be worth bringing up your issue with the [dittoseq repository ](https://github.com/dtm2451/dittoSeq) - don't know what exactly would be the issue. 

Nick

**Comment by Pedramto89** [comment]
Hi @ncborcherding 
Thank you. I opened an issue there!
