### ISSUE TITLE
Batch effect correction

### ISSUE THREAD

**Issue by Dragonmasterx87** [ncborcherding/escape#65]
Hi Nick!

Since enrichIt runs on counts data, how does enrichIT correct for sequencing depth and batch effects across the data? Wouldnt it be pertinent to be able to use the SCT slot as well? Is there a way to do this so that I can run enrichit using normalised data as well?

Cheers,
🐲

**Comment by ncborcherding** [comment]
Hey @Dragonmasterx87, 

Yes you should think about using normalized and/or integrated counts. I would recommend if using SCT, make sure to run ```PrepSCTFIndMarkers()``` which will correct the counts across each SCT model in the final seurat object. Then you can feed the count matrix into the ```enrichIt()``` function directly - if you use a seurat object it will pull from the RNA assay. 

Nick

**Comment by Dragonmasterx87** [comment]
Wow. Im really dumb. I didnt read this: `obj | The count matrix, Seurat, or SingleCellExperiment object.` 
Thanks, Nick, and sorry for the bother today. I have some ideas, but want to play around with escape a little and then enlist what I think would be useful.

Cheers,
🐲
