### ISSUE TITLE
About ANOVA results viz

### ISSUE THREAD

**Issue by Pedramto89** [ncborcherding/escape#66]
Hello

I did an ANOVA test for some enriched pathways resulting from ssGSEA. Now, I have some issues regarding the visualization of the results. Also, I am not sure how I can set a threshold to visualize only statistically significant results?

![Pasted Graphic](https://user-images.githubusercontent.com/85902042/222519753-66fe0cb1-21d8-41f2-8d97-3cb43b94bb45.png)

**Comment by ncborcherding** [comment]
Hey Pedram, 

Thanks for reaching out!

What are you trying to visualize exactly? 

In terms of thesholding the significance, this can be done using dplyr:

```
library(dplyr)
filtered <- Sig.Results %>%
       filter(p.value < 0.05) #you can change this for adjusted p-value or individual comparisons 
```

Thanks,
Nick

**Comment by Pedramto89** [comment]
Hi @ncborcherding  Thanks for being responsive!
I would filter out the pathways which pass a q-value < 0.05. There is a q-value column in my dataframe.

**Comment by ncborcherding** [comment]
You should then be able to get your results using: 

```
filtered <- Sig.Results %>%
       filter(q.value < 0.05)
```
