### ISSUE TITLE
Leading edge subset

### ISSUE THREAD

**Issue by basedank** [ncborcherding/escape#69]
Hello,

Thank you for developing this tool!

I have a few pathways that are enriched in some of my patients vs controls and I wanted to see what genes are driving those pathways, which is known as the leading edge subset (if I understand correctly). Is it possible to find this leading edge subset with escape?

Here's an example of the pathways I'd like to look at for those individuals:
![Screenshot 2023-05-25 at 11 32 08](https://github.com/ncborcherding/escape/assets/2665954/ecebb1ba-d1e6-455c-8121-eae8e0480071)

**Comment by ayin0510** [comment]
Hi @basedank! I'm assuming you used heatmapEnrichment() to generate that figure above--how were you able to get the annotations added at the top for cluster, disease status, etc.? I have been trying to figure out how to get annotations added to my heatmap of enrichment scores, so any insight would be greatly appreciated. Thanks in advance!
