### ISSUE TITLE
Normalization in enrichIt using 'UCell'

### ISSUE THREAD

**Issue by cr2106** [ncborcherding/escape#72]
Hey Nick

Thank you so much for developing another very useful tool for scRNA-seq analysis! I have a general question about the enrichment score obtained via enrichIt() with the UCell method. How is the gene set normalized?

Thank you and have a good day!

**Comment by ncborcherding** [comment]
Thanks for reaching out - 

The underlying implementation of UCell can be read more about [here](https://pubmed.ncbi.nlm.nih.gov/34285779/). The output of which is based on a Mann-Whitney U statistic. So it does not have a normalization step post-hoc for the enrichment values. 

I hope that helps and let me know if you have any other questions.

Nick
