### ISSUE TITLE
Prepare for upcoming Seurat v5 release

### ISSUE THREAD

**Issue by Gesmira** [ncborcherding/escape#73]
I am opening this issue as a notification because `escape` is listed [here](https://cran.r-project.org/web/packages/Seurat/index.html) as a package that relies (depends/imports/suggests) on Seurat. As you may know, we recently released Seurat v5 as a beta in March of this year, with new updates for spatial, multimodal, and massively scalable analysis. For more information on updates and improvements, check out our website https://satijalab.org/seurat/.
We are now preparing to release Seurat v5 to CRAN, and plan to submit it on October 23rd. While we have tried our best to keep things backward-compatible, it is possible that updates to Seurat and SeuratObject might break your existing functionality or tests. We wanted to reach out before the new version is on CRAN, so that there's time to report issues/incompatibilities and prepare you for any changes in your code base that might be necessary.

We apologize for any disruption or inconvenience, but hope that the improvements to Seurat v5 will benefit your users going forward.
To test the upcoming release, you can install Seurat from the `seurat5` branch using the instructions available on this page: https://satijalab.org/seurat/articles/install.

Thank you!
Seurat v5 team

**Comment by hvgogogo** [comment]
are there any way to solve this problem? thanks in advance.

> ES <- enrichIt(obj = at_sub_gs, gene.sets = gene.sets, groups = 1000, cores = 8,
+                min.size = NULL)
Error in cntEval(obj) : 
  no slot of name "counts" for this object of class "Assay5"

**Comment by ncborcherding** [comment]
Working on a new version release v2 that should be out soon with the support. 

Alternative for now is to run the count values directly by using SeuratObj@assay.... instead of just the SeuratObj.

Nick

**Comment by yesitsjess** [comment]
Any further advice on this? I'm getting:
```
> ES <- enrichIt(obj=obj_small, gene.sets=GS.hallmark, method="UCell", groups=1000, cores=2, min.size=5)
Error in cntEval(obj) : 
  no slot of name "counts" for this object of class "Assay5"
```
```
> ES <- enrichIt(obj=obj_small@assays, gene.sets=GS.hallmark, method="UCell", groups=1000, cores=2, min.size=5)
Error in Matrix(as.matrix(cnts), sparse = TRUE) : invalid 'data'
```
```
> ES <- enrichIt(obj=obj_small@assays$RNA, gene.sets=GS.hallmark, method="UCell", groups=1000, cores=2, min.size=5)
Error in as.vector(data) : 
  no method for coercing this S4 class to a vector
```

Seurat version 5.0.1
escape version 1.99.1

My seurat object looks like this:
```
> obj_small
An object of class Seurat 
36601 features across 262331 samples within 1 assay 
Active assay: RNA (36601 features, 0 variable features)
 1 layer present: counts
```

**Comment by adRn-s** [comment]
For the record, I had the same issue with Seurat v5, while my active assay was SCT. For now it's running, I had to pass `GetAssayData(SeuratObj, assay="RNA")` instead.
