### ISSUE TITLE
How to find Enriched pathways per seurat_cluster?

### ISSUE THREAD

**Issue by PrashINRA** [ncborcherding/escape#74]
Hi Nick,

I have 10 seurat cluster (A1 to A10) and I have generated enrichment score (ES2) for few thousands gene sets.
getSignificance(ES2, group = 'Celltypes', fit = 'ANOVA') gives me pairwise comparisons of different pathways like A2 vs A1, A3 vs A2 etc.
How can I get top enriched pathways per cluster like FindAllMarkers in Seurat?
Any hint?

Regards
Prashant

**Comment by ncborcherding** [comment]
Hey Prashant,

If you are interested in getting the output of ```FindAllMarkers()```, you might want to try adding the enrichment scores as an assay into the seurat object using the ```CreateAssayObject()``` function? 

Things to think about: 

- I would look into the statistical methods offered in Seurat to find an appropriate non-count-based method 
- It might be worth comparing ```enrichIt(..., ssGSEA.norm = FALSE)``` and ```enrichIt(..., ssGSEA.norm = TRUE)```

Nick
