### ISSUE TITLE
User Specification of cores Parameter is Seemingly Ignored

### ISSUE THREAD

**Issue by DarioS** [ncborcherding/escape#87]
I ran `enrichIt(fibroblasts, hallmarkSet, cores = 16)` but I only see two CPU at most being used in `top`. Also,

```r
Setting parallel calculations through a SnowParam back-end
with workers=16 and tasks=100.
Estimating ssGSEA scores for 50 gene sets.
```

but searching this repository for `SnowParam` only shows one use in vignette but none in function code. Was it accidentally deleted? Also can it be made so that users can pick `MulticoreParam` on Linux for memory efficiency? It doesn't seem possible to change it.

**Comment by ncborcherding** [comment]
Hey DarioS, 

Why you are not seeing reference to it in the repo here is that in escape v2, we are now passing the biocparallel argument using **BPPARAM**, where you can use any of the core arguments.

<img width="295" alt="Screenshot 2024-03-13 at 4 09 33 AM" src="https://github.com/ncborcherding/escape/assets/22754118/71fd5f8d-be02-4cd3-ae66-80ebf760a1fd">

It looks like you just updated to the dev version based on your other issues - so be sure to check out [this vignette](https://www.borch.dev/uploads/screpertoire/articles/running_escape) with the new updated functions.

Nick
