### ISSUE TITLE
ssGSEA Error About GSVA 

### ISSUE THREAD

**Issue by DarioS** [ncborcherding/escape#88]
I updated to the development version. The default settings fail due to some function call to GSVA.

```r
> runEscape(fibroblasts, hallmarkSet)
[1] "Using sets of 1000 cells. Running 35 times."
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘gsva’ for signature ‘"missing", "missing"’
```

**Comment by ncborcherding** [comment]
Hey Dario, 

This is a GSVA version issue that will be resolved with the next bioconductor release. 

For now, you can install GSVA from the repo using: 

```
devtools::install_github("rcastelo/GSVA")
```

Nick
