### ISSUE TITLE
Feature Request: Significance Without Class Labels

### ISSUE THREAD

**Issue by DarioS** [ncborcherding/escape#90]
Could there be a mode that doesn't require classes? I am trying to use the enrichment results to label cell types.

**Comment by ncborcherding** [comment]
Hey Dario, 

What do you mean classes? 

The enrichment calculations are done outside of classes - you can analyze the enrichment scores by any categorical variable (like clusters or cell type assignment). 

Nick

**Comment by DarioS** [comment]
What I mean is that the result is a matrix of cells by gene set scores. Could a same dimension matrix be made for p-values? I think `getSignificance` is for two-group comparisons but I wonder if each single cell can have a p-value for each pathway.

**Comment by ncborcherding** [comment]
Hey Dario, 

There are methods for annotation that will give you a confidence score based on a reference atlas (below are 2 good ones for R). Using enrichment scores might be an orthogonal method - but it is not asking which cell type is most likely or assigning a p-value, it is really saying across the ranked transcriptome, where are these gene lying.

1. [Azimuth](https://azimuth.hubmapconsortium.org/)
2. [Singler](https://bioconductor.org/packages/release/bioc/html/SingleR.html)
