### ISSUE TITLE
Error in runEscape

### ISSUE THREAD

**Issue by BaluPai** [ncborcherding/escape#92]
Hi,

Thanks for this helpful tool for single-cell analysis!
I have been recently trying Escape package following the nice tutorial: https://bioconductor.org/packages/release/bioc/vignettes/escape/inst/doc/vignette.html

But recently I tried to dig deeper, and wanted to try Normalization, additional visualization etc, like :https://www.borch.dev/uploads/screpertoire/articles/running_escape

Although I have installed escape and GSVA I am not able to use the function runEscape or escape.matrix !!
_Error in runEscape(object, method = "ssGSEA", gene.sets = GS.hallmark,  : 
  could not find function "runEscape"_
I also tried installing escape and gsva locally and calling it from local lib.

Any suggestions appreciated.

Best regards

**Comment by BaluPai** [comment]
Thanks Nick for following up on this!
Seems like there is also issues with Seurat v4 to v5 version too.
I re-installed escape (1.99.1) and GSVA (1.51.9) on local PC and HPC server. I can access the runEscape/escape.matrix() functions. 
But seems 'enrichIt()' is not available with this version, is that right?
I have few more queries regarding the normalization etc, which I would like to post later on separate thread.
Best,
Balu

**Comment by ncborcherding** [comment]
```enrichIt()``` has been supersceded by ```runEscape()``` and ```escape.matrix()``` - still tracking down issues with v5
