### ISSUE TITLE
Aboout function “runEscape” and “performNormalization”

### ISSUE THREAD

**Issue by DingfanGuo** [ncborcherding/escape#94]
https://www.borch.dev/uploads/screpertoire/articles/running_escape
I can't find this function in the version ‘1.12.0’ as follows.

> packageVersion('escape')
[1] ‘1.12.0’

Is this because of the version? How to install the latest version of escape?
I have tried  devtools and BiocManager to install.

Looking forward to your reply, thanks!

**Comment by ncborcherding** [comment]
Hey Dylan, 

The vignette is for v2 of escape - to install, you will need to first intall an update version of GSVA then escape from the github repo.

```
devtools::install_github("rcastelo/GSVA")
devtools::install_github("ncborcherding/escape")
```

Nick
